driver_license_number: A1234567
# "11051999" means Nov 5, 1999
dob: "11051999"
starting_addr: 123 Main Street
maps_api_key: <KEY>
email_person_name: Person Smith
mail_options:
  address: smtp.gmail.com
  port: 587
  user_name: personsmith@gmail.com
  password: thisIsAPassword
  authentication: plain
  enable_starttls_auto: true
